### ISSUE TITLE
Would you explain the meaning of "highest compression coefficient" of Jpeg?

### ISSUE THREAD

**Issue by chkimmmmm** [ando-khachatryan/HiDDeN#16]
Hello, Ando.

Thank you for sharing the great repo.

Thanks to this repo, I can understand paper.

I have a question about JPEG compression.

In the paper, they randomly picked the quality factor.

But your implementation does not have and you left the message 
"Jpeg the same as the Jpeg layer from the paper. It is a differentiable approximation of Jpeg compression with the highest compression coefficient."

Are you meaning current implementation is equal to Q = 50? 

Thank you.

**Comment by ando-khachatryan** [comment]
Hi, 
The Jpeg layer in here is exactly the Jpeg-Mask layer from the paper. 
This is the differentiable approximation of Jpeg with Q=50.
Are you sure about the jpeg quality being varied in the paper?  I could not find that they are varying the strength of differentiable Jpeg compression. In figure 10, they show the accuracy vs Jpeg compression Q, but that's not the noise layer Q (i.e. Jpeg-Mask), but the real Jpeg compression Q which they used to validate the model.

**Comment by chkimmmmm** [comment]
Thank you for fast reply. 
I totally agree with you.

Maybe, I would misunderstand the paper's point.
In page 6 of the paper, they said quality factor Q in (0,100).
And end of the paragraph, they mention one more JPEG has quality factor. 
But their approximation experiment, they compare with Q = 50.

**Comment by ando-khachatryan** [comment]
You're right, they do mention Q as variable on page 6.
However, Figure 10 explicitly says:
 "The specialized JPEG model is trained on the differentiable approximation JPEG-Mask, and the plot shows performance on actual JPEG."
Figure 11 is less clear, whether the Jpeg figure is diff. approximation or real Jpeg compression. 

Anyway, if you want variable-Q jpeg, you can do the it relatively easily. The noise_layers/jpeg_compression.py has a class JpegCompression class, which has the following constructor:
```
def __init__(self, device, yuv_keep_weights = (25, 9, 9)):
...
```
the (25,9,9) are the number of coefficients in Y,U,V channels which Jpeg-Mask with Q=50 keeps. If you want compression with another Q-level, just look up the number of coefficients jpeg keeps for that level of Q, and create JpegCompression with yuv_keep_weights = (y_q, u_q, v_q) instead of (25,9,9).

Hope this helps.

**Comment by chkimmmmm** [comment]
Thank you so much!
It really helps me.
Have a great day!

**Comment by zyuan-jiang** [comment]
> 

Hello, you reply helps me a lot! 

I still have a question:
How can I know the number of coefficients jpeg keeps for different level of quality factor Q ?
