### ISSUE TITLE
Can capacity increase？

### ISSUE THREAD

**Issue by LeeeLiu** [ando-khachatryan/HiDDeN#21]
Hello，
in  your  steganography experiment，
binary messages of length L is 52，cover image is 16×16（grayscale）。
Can  L  be  longer?  that's to say，can capacity increase？

**Comment by ando-khachatryan** [comment]
Note that I'm not the original author. I have not done any steganography experiments myself, only watermarking.

You can increase L and see if the network trains, and inspect the encoded images to make sure they are not distorted too much. It might be the case that in order to train with larger capacity, you need to change some hyperparameters. Also, with the HiDDeN architecture, message length affects the amount of GPU RAM you need for training.

As mentioned, I'm not interested in steganography and haven't done touched this project for some time, so take the above with a grain of salt.

**Comment by LeeeLiu** [comment]
OK, I got it.&nbsp; thanks!



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 27, 2021 03:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ando-khachatryan/HiDDeN] Can capacity increase？ (#21)




 
Note that I'm not the original author. I have not done any steganography experiments myself, only watermarking.
 
You can increase L and see if the network trains, and inspect the encoded images to make sure they are not distorted too much. It might be the case that in order to train with larger capacity, you need to change some hyperparameters. Also, with the HiDDeN architecture, message length affects the amount of GPU RAM you need for training.
 
As mentioned, I'm not interested in steganography and haven't done touched this project for some time, so take the above with a grain of salt.

**Comment by LeeeLiu** [comment]
Got it. Thanks!
